<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Extreme Weather and Next-Day TSX Returns – Extreme Weather and TSX Returns</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-35155b22413c9ef7a79a96887d465071.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Extreme Weather and TSX Returns</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page"> 
<span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./viz.html"> 
<span class="menu-text">Interactive Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./figures.html"> 
<span class="menu-text">Figures</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/hugo-fuhrer/JSC370-finalproject"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">GitHub</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">2</span> Methods</a>
  <ul class="collapse">
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition"><span class="header-section-number">2.1</span> Data acquisition</a></li>
  <li><a href="#data-missingness" id="toc-data-missingness" class="nav-link" data-scroll-target="#data-missingness"><span class="header-section-number">2.2</span> Data missingness</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">2.3</span> Feature engineering</a></li>
  <li><a href="#traintest-split-and-model-selection" id="toc-traintest-split-and-model-selection" class="nav-link" data-scroll-target="#traintest-split-and-model-selection"><span class="header-section-number">2.4</span> Train/test split and model selection</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#weather" id="toc-weather" class="nav-link" data-scroll-target="#weather"><span class="header-section-number">3.1</span> Weather</a></li>
  <li><a href="#returns" id="toc-returns" class="nav-link" data-scroll-target="#returns"><span class="header-section-number">3.2</span> Returns</a></li>
  <li><a href="#extreme-vs.-normal-days" id="toc-extreme-vs.-normal-days" class="nav-link" data-scroll-target="#extreme-vs.-normal-days"><span class="header-section-number">3.3</span> Extreme vs.&nbsp;normal days</a></li>
  </ul></li>
  <li><a href="#models" id="toc-models" class="nav-link" data-scroll-target="#models"><span class="header-section-number">4</span> Models</a>
  <ul class="collapse">
  <li><a href="#performance" id="toc-performance" class="nav-link" data-scroll-target="#performance"><span class="header-section-number">4.1</span> Performance</a></li>
  <li><a href="#variable-importance" id="toc-variable-importance" class="nav-link" data-scroll-target="#variable-importance"><span class="header-section-number">4.2</span> Variable importance</a></li>
  <li><a href="#partial-dependence" id="toc-partial-dependence" class="nav-link" data-scroll-target="#partial-dependence"><span class="header-section-number">4.3</span> Partial dependence</a></li>
  </ul></li>
  <li><a href="#summary-of-findings" id="toc-summary-of-findings" class="nav-link" data-scroll-target="#summary-of-findings"><span class="header-section-number">5</span> Summary of findings</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">5.1</span> Limitations</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Extreme Weather and Next-Day TSX Returns</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>The last four decades have been hotter than any period since records began in 1850, with 2015–2024 constituting the warmest decade on record (UN, 2024). Climate change, however, extends well beyond rising average temperatures — it reshapes precipitation patterns, storm intensity, and the frequency of extreme events worldwide. In Ontario specifically, a report from the Climate Risk Institute found that mean annual temperatures increased by 1.0–1.5 °C between 1948 and 2012. The downstream consequences have already materialized: declining Great Lakes ice cover, a 9.7% normalized increase in the rain fraction of total precipitation, more volatile lake levels, fewer extreme cold days, and a significant rise in days exceeding 30 °C. These shifts manifest as floods, wildfires, and heatwaves of growing intensity and frequency.</p>
<p>The economic strain from these events is substantial and cascading. Disaster recovery drives up insurance premiums and diverts public expenditure; utilities absorb restoration costs and foregone revenue; energy firms face volatile demand swings; and retailers suffer disrupted foot traffic. Financial institutions are exposed less directly but no less materially — through mortgage portfolios on properties at elevated flood or fire risk, and through credit extended to small businesses whose operations are weather-sensitive (Canada.ca).</p>
<p>To investigate these economic impacts empirically, we use equity returns as a high-frequency proxy for economic activity. Financial data offer a practical advantage over slower indicators such as GDP revisions, insurance claims, or post-disaster damage surveys: stock prices are continuously recorded, publicly available, and react in near real-time to new information. If extreme-weather signals are detectable in daily returns, equity markets can function as a real-time sensor of physical climate impacts — complementing, rather than replacing, the broader toolkit of climate economics.</p>
<p>We focus on 15 TSX-listed companies with material Ontario exposure, spanning seven sectors: banks (TD, RY, CM, BNS, BMO), insurance (IFC, MFC, POW), utilities (FTS, EMA), energy (ENB, SU), telecom (BCE), real estate (REI-UN), and retail (L), benchmarked against XIU.TO (the iShares S&amp;P/TSX 60 ETF). These are paired with daily climate observations from up to 178 Environment Canada weather stations across southern Ontario over the period 2008–2024 (114–151 stations are active in any given year).</p>
<p>We address two empirical questions:</p>
<ol type="1">
<li><strong>Regression:</strong> Does an extreme-weather day in Ontario produce a measurably different next-day log return for these tickers?</li>
<li><strong>Classification:</strong> Does extreme weather shift the probability that the next-day return is positive?</li>
</ol>
<p>These questions carry significance beyond portfolio management. A validated weather–return signal provides empirical evidence that extreme weather creates measurable, near-term economic disruption — a link that can directly strengthen the case for climate adaptation investment at the provincial and municipal level. Infrastructure expenditures on flood defences, grid hardening, and urban heat mitigation routinely face political resistance on cost grounds; quantifying the next-day economic footprint of extreme events gives planners concrete, market-derived evidence to cite. As the Government of Canada notes, every dollar spent on climate adaptation saves up to $15 in long-term damage and mitigation costs — and a market-validated signal makes that calculus harder to dismiss.</p>
</section>
<section id="methods" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="methods"><span class="header-section-number">2</span> Methods</h2>
<section id="data-acquisition" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="data-acquisition"><span class="header-section-number">2.1</span> Data acquisition</h3>
<p>Weather data comes from the Meteorological Service of Canada GeoMet OGC API (<code>api.weather.gc.ca</code>). For each of the 178 stations active in the 2008–2024 range within our southern Ontario bounding box (lon <span class="math inline">\(\in [-83,-74.5]\)</span>, lat <span class="math inline">\(\in [41.5, 46.5]\)</span>), we paginate through the <code>/collections/climate-daily/items</code> endpoint and collect six daily variables: mean, max, and min temperature (°C), total precipitation (mm), total snowfall (cm), and the maximum wind gust (km/h).</p>
<p>Stock prices are pulled with the <code>yfinance</code> package, which uses Yahoo Finance’s public endpoints. We download adjusted closing prices for the 15 tickers plus XIU.TO and convert to daily log returns <span class="math inline">\(r_t = \ln(P_t / P_{t-1})\)</span>.</p>
</section>
<section id="data-missingness" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="data-missingness"><span class="header-section-number">2.2</span> Data missingness</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dataset</th>
<th style="text-align: right;">Rows</th>
<th>Variable</th>
<th style="text-align: right;">% Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>raw_weather (per-station daily)</td>
<td style="text-align: right;">761,060</td>
<td>max_gust</td>
<td style="text-align: right;">63.38</td>
</tr>
<tr class="even">
<td>raw_weather (per-station daily)</td>
<td style="text-align: right;">761,060</td>
<td>total_snow</td>
<td style="text-align: right;">47.92</td>
</tr>
<tr class="odd">
<td>raw_weather (per-station daily)</td>
<td style="text-align: right;">761,060</td>
<td>mean_temp</td>
<td style="text-align: right;">14.57</td>
</tr>
<tr class="even">
<td>raw_weather (per-station daily)</td>
<td style="text-align: right;">761,060</td>
<td>total_precip</td>
<td style="text-align: right;">13.90</td>
</tr>
<tr class="odd">
<td>raw_weather (per-station daily)</td>
<td style="text-align: right;">761,060</td>
<td>max_temp</td>
<td style="text-align: right;">11.31</td>
</tr>
</tbody>
</table>
<p>The raw weather data was collected from 178 stations in total, although there is fluctuation in how many are active in any given year (114–151) and how many variables they report on any given day. This is reflected in the per-station daily missingness, where snow and max gust are missing 48% and 63% respectively. Aggregating these variables across all reporting stations on each day removes the per-station missingness and produces a daily series that aligns cleanly with the trading data, which had 0% missingness.</p>
</section>
<section id="feature-engineering" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="feature-engineering"><span class="header-section-number">2.3</span> Feature engineering</h3>
<p>Extreme-weather flags are based on whole-period percentile thresholds: <code>extreme_cold</code> = mean temperature in the bottom 5%, <code>extreme_heat</code> = top 5%, <code>extreme_precip</code> = top 5% of total precipitation, <code>extreme_wind</code> = top 5% of maximum gust. <code>extreme_any</code> is set to 1 if any individual flag is up for that day.</p>
<p>We add continuous features in an attempt to capture more detail than the binary flags: standardised mean temperature (<code>temp_z</code>), a 5-day temperature anomaly (<code>temp_5d_anom</code>, the deviation of today’s mean from the trailing 5-day mean), standardised precipitation, and standardised wind. For the financial side, we include lagged returns (<span class="math inline">\(r_{t-1}\)</span>, <span class="math inline">\(r_{t-2}\)</span>), a 5-day rolling mean and 5-day rolling volatility, and the contemporaneous market return (XIU.TO log return on day <span class="math inline">\(t\)</span>, controlling for the broad market factor). Calendar features (<code>month</code>, <code>dow</code>) capture seasonality and weekday effects, and one-hot sector dummies allow the models to capture differences across sectors. All rolling and lagged features use only information available at time <span class="math inline">\(t-1\)</span> to avoid look-ahead bias. The final feature set has 21 predictors; the outcome is either the next-day log return for regression or its sign for classification.</p>
</section>
<section id="traintest-split-and-model-selection" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="traintest-split-and-model-selection"><span class="header-section-number">2.4</span> Train/test split and model selection</h3>
<p>To respect the time-series structure we use a chronological split: training data is everything before 2022-01-01, and the test set is 2022-01-01 onwards.</p>
<p>The four models are:</p>
<ul>
<li><strong>Naive baseline</strong> — predict the training-period mean for every test observation.</li>
<li><strong>Random Forest</strong> — 200 trees, <code>max_features = sqrt(p)</code>, <code>min_samples_leaf = 10</code>, OOB scoring on. The classifier uses identical hyperparameters.</li>
<li><strong>XGBoost</strong> — a 5-iteration randomized search over <code>max_depth ∈ {3,4,5,6}</code>, <code>learning_rate ∈ {0.03, 0.05, 0.1}</code>, <code>reg_lambda ∈ {1, 10}</code>, <code>subsample ∈ {0.85, 1.0}</code>, with 3 chronological CV folds and negative-RMSE scoring. The selected configuration was <code>max_depth=4, learning_rate=0.05, reg_lambda=10, reg_alpha=0.1</code>, with early stopping at roughly 80 boosting rounds.</li>
<li><strong>GAM</strong> — smooth splines on the 7 continuous features (mean temp, total precip, max gust, 5-day temp anomaly, lagged return, 5-day vol, market return) plus a factor term for <code>extreme_any</code>.</li>
</ul>
<p>Reported test statistics are RMSE, MAE, and <span class="math inline">\(R^2\)</span> for regression; accuracy and ROC-AUC for classification. We additionally show variable importance, partial dependence (XGBoost) and partial-effect curves (GAM), and a bias-variance curve.</p>
</section>
</section>
<section id="results" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="results"><span class="header-section-number">3</span> Results</h2>
<p>We split the results into two parts: the first reports descriptive findings directly from the data, and the second discusses the machine-learning models.</p>
<section id="weather" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="weather"><span class="header-section-number">3.1</span> Weather</h3>
<p><strong>Table 1.</strong> Summary statistics for the four core daily weather variables, aggregated across all reporting stations (n = 6,210 days, 2008–2024).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">std</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">5%</th>
<th style="text-align: right;">25%</th>
<th style="text-align: right;">50%</th>
<th style="text-align: right;">75%</th>
<th style="text-align: right;">95%</th>
<th style="text-align: right;">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean Temp (°C)</td>
<td style="text-align: right;">6,210</td>
<td style="text-align: right;">7.71</td>
<td style="text-align: right;">10.63</td>
<td style="text-align: right;">−22.28</td>
<td style="text-align: right;">−10.63</td>
<td style="text-align: right;">−0.57</td>
<td style="text-align: right;">8.11</td>
<td style="text-align: right;">17.22</td>
<td style="text-align: right;">22.48</td>
<td style="text-align: right;">28.56</td>
</tr>
<tr class="even">
<td>Total Precip (mm)</td>
<td style="text-align: right;">6,210</td>
<td style="text-align: right;">18.18</td>
<td style="text-align: right;">19.11</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">4.70</td>
<td style="text-align: right;">12.60</td>
<td style="text-align: right;">25.18</td>
<td style="text-align: right;">55.00</td>
<td style="text-align: right;">240.00</td>
</tr>
<tr class="odd">
<td>Total Snow (cm)</td>
<td style="text-align: right;">6,210</td>
<td style="text-align: right;">3.58</td>
<td style="text-align: right;">7.15</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: right;">71.00</td>
</tr>
<tr class="even">
<td>Max Gust (km/h)</td>
<td style="text-align: right;">6,210</td>
<td style="text-align: right;">60.75</td>
<td style="text-align: right;">17.60</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">37.00</td>
<td style="text-align: right;">48.00</td>
<td style="text-align: right;">59.00</td>
<td style="text-align: right;">71.00</td>
<td style="text-align: right;">91.00</td>
<td style="text-align: right;">220.00</td>
</tr>
</tbody>
</table>
<p>Table 1 summarises the distributions of the core weather variables. Mean daily temperature sits at 7.71 °C with a wide standard deviation of 10.63 °C. It follows a somewhat bimodal distribution as per Figure 1, with one mode just above 0 °C and another just under 20 °C. Both the table and figure show the 5% and 95% thresholds used to define extreme cold and extreme heat days, corresponding to −10.63 °C and 22.48 °C. As expected, precipitation, snow, and gust are all bounded below by zero and right-skewed.</p>
<div id="fig-temp-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-temp-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig01_temp_distribution.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-temp-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <strong>Figure 1.</strong> Distribution of Ontario daily mean temperature (2008–2024, n = 6,210 days). Dashed lines mark the 5th and 95th percentiles used to define <code>extreme_cold</code> and <code>extreme_heat</code>. The bimodal shape reflects the seasonal split between winter and summer modes typical of southern Ontario.
</figcaption>
</figure>
</div>
<p>We dive a bit deeper into extreme-weather days with Figure 2; no obvious trends are present at this 17-year time scale, although the longer-horizon trends documented in the climate literature (records starting in the 1800s) are well established.</p>
<div id="fig-extreme-counts" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-extreme-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig02_extreme_counts.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-extreme-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: <strong>Figure 2.</strong> Annual count of extreme-weather days by type. Each colour is a percentile threshold; bars are dodged for visual comparison.
</figcaption>
</figure>
</div>
</section>
<section id="returns" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="returns"><span class="header-section-number">3.2</span> Returns</h3>
<p><strong>Table 2.</strong> Per-ticker mean daily log return (in %), annualized volatility (in %), and number of trading days (2008–2024).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ticker</th>
<th>Sector</th>
<th style="text-align: right;">Mean Daily Ret (%)</th>
<th style="text-align: right;">Ann. Volatility (%)</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BCE.TO</td>
<td>Telecom</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">20.92</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="even">
<td>BMO.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">23.24</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="odd">
<td>BNS.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">22.40</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="even">
<td>CM.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.043</td>
<td style="text-align: right;">23.57</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="odd">
<td>EMA.TO</td>
<td>Utilities</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">17.59</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="even">
<td>ENB.TO</td>
<td>Energy</td>
<td style="text-align: right;">0.045</td>
<td style="text-align: right;">22.59</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="odd">
<td>FTS.TO</td>
<td>Utilities</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">18.65</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="even">
<td>IFC.TO</td>
<td>Insurance</td>
<td style="text-align: right;">0.054</td>
<td style="text-align: right;">21.59</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="odd">
<td>L.TO</td>
<td>Retail</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">19.83</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="even">
<td>MFC.TO</td>
<td>Insurance</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">33.32</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="odd">
<td>POW.TO</td>
<td>Insurance</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">26.13</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="even">
<td>REI-UN.TO</td>
<td>REIT</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">22.78</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="odd">
<td>RY.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.046</td>
<td style="text-align: right;">21.89</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="even">
<td>SU.TO</td>
<td>Energy</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">38.48</td>
<td style="text-align: right;">4,261</td>
</tr>
<tr class="odd">
<td>TD.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">22.07</td>
<td style="text-align: right;">4,261</td>
</tr>
</tbody>
</table>
<p>Mean daily log returns range from 0.009% (SU.TO — Energy) to 0.054% (IFC.TO — Insurance), with a volatility ordering that roughly tracks Energy and Insurance as the most volatile (SU.TO at 38.5%, MFC.TO at 33.3%), Utilities and Retail at the low end (EMA.TO at 17.6%, FTS.TO at 18.7%, L.TO at 19.8%), and Banks somewhere in between (~22–24%).</p>
<p>Patterns emerge over time in Figure 3, where we clearly see the 2008 financial crisis and the 2020 COVID drawdown across every sector, confirming that the broad market factor dominates daily movement. We also see dispersion among sectors, with banks and retail compounding faster than utilities, telecom, or the real estate trust.</p>
<div id="fig-cum-returns" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cum-returns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig03_cumulative_returns.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cum-returns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: <strong>Figure 3.</strong> Cumulative log returns by sector, 2008–2024. The 2008 financial crisis and 2020 COVID shock are visible across all sectors.
</figcaption>
</figure>
</div>
</section>
<section id="extreme-vs.-normal-days" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="extreme-vs.-normal-days"><span class="header-section-number">3.3</span> Extreme vs.&nbsp;normal days</h3>
<p><strong>Table 3.</strong> Mean next-day log return (in %) on normal vs.&nbsp;extreme-weather days, with the difference in basis points (1 bp = 0.01%).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ticker</th>
<th>Sector</th>
<th style="text-align: right;">Normal (%)</th>
<th style="text-align: right;">Extreme (%)</th>
<th style="text-align: right;">Diff (bp)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BCE.TO</td>
<td>Telecom</td>
<td style="text-align: right;">0.0138</td>
<td style="text-align: right;">0.0330</td>
<td style="text-align: right;">+1.92</td>
</tr>
<tr class="even">
<td>BMO.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.0328</td>
<td style="text-align: right;">0.0679</td>
<td style="text-align: right;">+3.51</td>
</tr>
<tr class="odd">
<td>BNS.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.0288</td>
<td style="text-align: right;">0.0346</td>
<td style="text-align: right;">+0.58</td>
</tr>
<tr class="even">
<td>CM.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.0361</td>
<td style="text-align: right;">0.0719</td>
<td style="text-align: right;">+3.58</td>
</tr>
<tr class="odd">
<td>EMA.TO</td>
<td>Utilities</td>
<td style="text-align: right;">0.0350</td>
<td style="text-align: right;">0.0630</td>
<td style="text-align: right;">+2.80</td>
</tr>
<tr class="even">
<td>ENB.TO</td>
<td>Energy</td>
<td style="text-align: right;">0.0491</td>
<td style="text-align: right;">0.0274</td>
<td style="text-align: right;">−2.17</td>
</tr>
<tr class="odd">
<td>FTS.TO</td>
<td>Utilities</td>
<td style="text-align: right;">0.0216</td>
<td style="text-align: right;">0.0788</td>
<td style="text-align: right;">+5.72</td>
</tr>
<tr class="even">
<td>IFC.TO</td>
<td>Insurance</td>
<td style="text-align: right;">0.0461</td>
<td style="text-align: right;">0.0893</td>
<td style="text-align: right;">+4.32</td>
</tr>
<tr class="odd">
<td>L.TO</td>
<td>Retail</td>
<td style="text-align: right;">0.0655</td>
<td style="text-align: right;">−0.0060</td>
<td style="text-align: right;">−7.15</td>
</tr>
<tr class="even">
<td>MFC.TO</td>
<td>Insurance</td>
<td style="text-align: right;">0.0097</td>
<td style="text-align: right;">0.0593</td>
<td style="text-align: right;">+4.96</td>
</tr>
<tr class="odd">
<td>POW.TO</td>
<td>Insurance</td>
<td style="text-align: right;">0.0177</td>
<td style="text-align: right;">0.0492</td>
<td style="text-align: right;">+3.15</td>
</tr>
<tr class="even">
<td>REI-UN.TO</td>
<td>REIT</td>
<td style="text-align: right;">0.0155</td>
<td style="text-align: right;">0.0472</td>
<td style="text-align: right;">+3.17</td>
</tr>
<tr class="odd">
<td>RY.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.0365</td>
<td style="text-align: right;">0.0842</td>
<td style="text-align: right;">+4.77</td>
</tr>
<tr class="even">
<td>SU.TO</td>
<td>Energy</td>
<td style="text-align: right;">0.0082</td>
<td style="text-align: right;">0.0161</td>
<td style="text-align: right;">+0.79</td>
</tr>
<tr class="odd">
<td>TD.TO</td>
<td>Bank</td>
<td style="text-align: right;">0.0328</td>
<td style="text-align: right;">0.0461</td>
<td style="text-align: right;">+1.33</td>
</tr>
</tbody>
</table>
<p>Table 3 shows the difference in basis points between mean returns on normal days and on days following an extreme-weather event. Most differences are positive, with Utilities (FTS.TO at +5.72 bp, EMA.TO at +2.80 bp) and Insurance (IFC.TO at +4.32 bp, MFC.TO at +4.96 bp) showing a plausible economic mechanism — increased energy demand and premium revisions, respectively — while Retail (L.TO at −7.15 bp) is one of only two negative differences, potentially explained by reduced foot traffic or forced closures. We must keep in mind, however, that these differences are all well within the daily volatility of each ticker and are not formally tested for significance, so they should not be over-interpreted. Figures 4 and 5 reinforce this visually: distributions overlap almost completely in the histogram, and the interquartile boxes overlap entirely in the boxplots, showing that if a signal exists, it is small relative to noise.</p>
<div id="fig-ndr-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ndr-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig04_ndr_distribution.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ndr-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: <strong>Figure 4.</strong> Next-day log return distribution by ticker, split by whether the previous day was an extreme-weather day.
</figcaption>
</figure>
</div>
<div id="fig-box-sector" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-box-sector-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig05_box_by_sector.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-box-sector-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: <strong>Figure 5.</strong> Next-day return boxplots by sector and weather regime. Bands are tight at the 25th–75th percentiles around zero; the difference between extreme and normal medians is too small to see at the box scale.
</figcaption>
</figure>
</div>
<p>The temperature-vs-returns scatter in Figure 6 shows a flat slope with a 95% confidence interval containing zero, confirming there is no linear relationship at the aggregate monthly level.</p>
<div id="fig-monthly-temp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-monthly-temp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig06_monthly_temp_vs_ndr.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monthly-temp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: <strong>Figure 6.</strong> Monthly mean Ontario temperature vs.&nbsp;average next-day TSX return.
</figcaption>
</figure>
</div>
<p>In the correlation heatmap (Figure 7) the strongest off-diagonal correlations are between weather features themselves (e.g.&nbsp;0.28 between mean temperature and total precipitation, −0.17 between max gust and temperature). Notably, every weather feature has near-zero correlation with next-day market returns.</p>
<div id="fig-corr-heat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corr-heat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig07_correlation_heatmap.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-corr-heat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: <strong>Figure 7.</strong> Correlation matrix between weather features (mean_temp, total_precip, max_gust, temp_5d_anom) and return features (lagged_return, mkt_return, next_day_return).
</figcaption>
</figure>
</div>
</section>
</section>
<section id="models" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="models"><span class="header-section-number">4</span> Models</h2>
<p>The final feature matrix contained 21 columns: 8 weather features (mean temp, total precip, total snow, max gust, 5-day temp anomaly, and four binary <code>extreme_*</code> flags), 5 financial controls (lagged return, 2-day lagged return, rolling 5-day return, rolling 5-day volatility, market return), 2 calendar features (day-of-week, calendar month), and 6 sector dummies. To avoid look-ahead bias, the data was split chronologically rather than randomly: the test period (2022–2024) lies entirely after the training period (2008–2021).</p>
<p>For regression, four models were trained and compared on the same test set: a mean baseline, a Random Forest regressor (200 trees, <code>max_features='sqrt'</code>, <code>min_samples_leaf=10</code>), a tuned XGBoost regressor (selected via 3-fold chronological CV: <code>max_depth=4</code>, <code>learning_rate=0.05</code>, <code>reg_lambda=10</code>, <code>reg_alpha=0.1</code>, with early stopping at roughly 80 rounds), and a GAM with smooth terms on each continuous feature. For classification, we used the encoded binary outcome <code>next_day_return &gt; 0</code> and trained Random Forest and XGBoost classifiers with equivalent hyperparameters, evaluated by accuracy and ROC-AUC.</p>
<section id="performance" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="performance"><span class="header-section-number">4.1</span> Performance</h3>
<p><strong>Table 4.</strong> Test-set regression performance (test period: 2022-01-01 onward). OOB R² is reported only for the Random Forest, where it is computed within the training period on bootstrap-excluded observations.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Test RMSE</th>
<th style="text-align: right;">Test MAE</th>
<th style="text-align: right;">Test R²</th>
<th style="text-align: right;">OOB R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Naive (train mean)</td>
<td style="text-align: right;">0.01182</td>
<td style="text-align: right;">0.00852</td>
<td style="text-align: right;">−0.0000</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td style="text-align: right;">0.01194</td>
<td style="text-align: right;">0.00860</td>
<td style="text-align: right;">−0.0203</td>
<td style="text-align: right;">0.286</td>
</tr>
<tr class="odd">
<td>XGBoost</td>
<td style="text-align: right;">0.01191</td>
<td style="text-align: right;">0.00857</td>
<td style="text-align: right;">−0.0147</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>GAM</td>
<td style="text-align: right;">0.01320</td>
<td style="text-align: right;">0.00882</td>
<td style="text-align: right;">−0.2460</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<p>The main finding is that no model beats the naive baseline on the test set. Test <span class="math inline">\(R^2\)</span> is slightly negative for the tree-based models (Random Forest: −0.020; XGBoost: −0.015) and meaningfully negative for the GAM (−0.246), meaning predicting the train mean for every observation would have produced a lower test RMSE than any of the trained models. Two complementary explanations are at work.</p>
<p>First, Figure 8 (bias–variance trade-off for XGBoost) shows training RMSE falling monotonically from 0.0150 to 0.0130 as boosting rounds increase from 20 to 200, while test RMSE stays flat. This is the model fitting noise rather than signal, and it validates the early-stopping strategy used in the final fit.</p>
<div id="fig-bv" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig14_bias_variance.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: <strong>Figure 8.</strong> Bias-variance trade-off for XGBoost as a function of boosting rounds.
</figcaption>
</figure>
</div>
<p>Second, the Random Forest’s out-of-bag <span class="math inline">\(R^2\)</span> of 0.286 is dramatically higher than its test <span class="math inline">\(R^2\)</span> of −0.020. The OOB estimate is computed on bootstrap-excluded observations <em>within</em> the 2008–2021 training period, so the gap to the test set primarily reflects distribution shift between training and test periods rather than overfitting alone — post-COVID monetary policy, interest-rate normalization, and inflation dynamics from 2022 onward have no comparable analogue in 2008–2021.</p>
<p>The same point appears in Figure 9, where predictions are tightly compressed near zero (vertical range roughly ±0.5%) while actuals span ±10%.</p>
<div id="fig-pred-vs-actual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pred-vs-actual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig12_pred_vs_actual.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pred-vs-actual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: <strong>Figure 9.</strong> XGBoost test-set predicted vs.&nbsp;actual next-day returns.
</figcaption>
</figure>
</div>
</section>
<section id="variable-importance" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="variable-importance"><span class="header-section-number">4.2</span> Variable importance</h3>
<p>Although the models do not predict well, comparing variable importance across algorithms tells us which features they were trying to use.</p>
<p>Figures 10 and 11 (XGBoost and Random Forest) mostly agree on the ranking. In XGBoost, the top-importance feature is <code>temp_5d_anom</code> (5-day temperature anomaly, gain ≈ 0.106), followed by <code>extreme_wind</code> (0.102), <code>mkt_return</code> (0.085), and <code>dow</code> (day-of-week, 0.076). In Random Forest, <code>mkt_return</code> dominates (importance ≈ 0.182), followed by <code>roll5_return</code> (0.102), <code>roll5_vol</code> (0.100), <code>temp_5d_anom</code> (0.099), and <code>lag2_return</code> (0.090). The two models agree on three points: the market return dominates; lagged and rolling return features provide some utility; and at least one weather feature (the 5-day temperature anomaly) consistently ranks in the top 5. Sector dummies (<code>sec_*</code>) and binary <code>extreme_*</code> flags rank near the bottom in both models, indicating that sector differences are weak in this setup and that continuous features carry a higher proportion of whatever signal is available.</p>
<div id="fig-xgb-imp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-xgb-imp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig08_xgb_importance.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-xgb-imp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: <strong>Figure 10.</strong> XGBoost feature importance (mean gain) for the top 15 predictors.
</figcaption>
</figure>
</div>
<div id="fig-rf-imp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rf-imp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig09_rf_importance.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rf-imp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: <strong>Figure 11.</strong> Random Forest feature importance.
</figcaption>
</figure>
</div>
</section>
<section id="partial-dependence" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="partial-dependence"><span class="header-section-number">4.3</span> Partial dependence</h3>
<p>Figure 12 (XGBoost partial dependence) shows the marginal effects for the six top features. The <code>mkt_return</code> panel has the most pronounced shape — approximately linear and strongly increasing. We can interpret this as a sharp increase in the market yesterday (say +1.5%) driving the model to predict next-day returns ~0.001 higher than at zero market return. The <code>lagged_return</code> panel shows a small negative slope, most likely indicating regression to the mean. The <code>roll5_vol</code> panel shows that returns predicted on high-volatility days are slightly higher (a risk premium). The other panels are essentially flat or noisy.</p>
<div id="fig-pdp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig10_pdp.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: <strong>Figure 12.</strong> Partial dependence plots — tuned XGBoost.
</figcaption>
</figure>
</div>
<p>Figure 13 tells a slightly different story. The GAM’s smooth on <code>mkt_return</code> is monotonically negative with sharp curvature and a narrow confidence interval; <code>roll5_vol</code> shows a strong negative slope (high recent volatility predicts lower next-day returns); <code>lagged_return</code> is U-shaped, suggesting both very-negative and very-positive lagged returns predict positive next-day returns. The weather smooths (<code>mean_temp</code>, <code>total_precip</code>, <code>max_gust</code>, <code>temp_5d_anom</code>) are mostly flat with wide 95% bands that cover zero across nearly the full input range — only the extreme right tails (e.g.&nbsp;max gust &gt;100 km/h) show any deviation, and even there the band is wide. The <code>Extreme Day</code> discrete-effect panel shows extreme days have a negative partial effect of ~−0.00015 (≈ −1.5 bp in log return) once continuous features are controlled for, which contradicts the descriptive Table 3 finding and reinforces that the table was capturing market-level patterns rather than weather-driven movement.</p>
<div id="fig-gam" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig11_gam_partial.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: <strong>Figure 13.</strong> GAM partial-effect curves with 95% confidence intervals.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="summary-of-findings" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="summary-of-findings"><span class="header-section-number">5</span> Summary of findings</h2>
<p>Across all analyses the picture is consistent: there is a small, mechanically plausible association between extreme-weather days and slightly higher next-day returns for utilities, banks, and insurers (Table 3, +1 to +6 bp), and 5-day temperature anomalies appear in the top-5 most important features for both tree-based regressors. However, the weather signal is dominated by market-return and lagged-return features in every model, and is not strong enough for any model to outperform a naive train-mean predictor. Returns appear to be effectively unpredictable from this feature set on the daily horizon, and this null result is itself the answer to the research question: at the daily frequency, the relationship between Ontario weather and TSX-Ontario returns is too weak to be exploited.</p>
<section id="limitations" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="limitations"><span class="header-section-number">5.1</span> Limitations</h3>
<p>Most importantly, the daily horizon may not be the right approach. Extreme-weather damage may better manifest itself in quarterly earnings (insurance claims, utility restoration costs) than in next-day prices. A follow-up analysis at weekly, monthly, or longer horizons would likely surface stronger or different effects. Second, our aggregation of weather averages out spatial variation that may matter for specific firms — a province-wide mean conceals the localized storm or heat dome that actually disrupts a given facility. Third, each company varies in its exposure to Ontario specifically; some of these names have material operations elsewhere in Canada or internationally, diluting any Ontario-weather signal in their returns.</p>
<hr>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/hugo-fuhrer\.github\.io\/JSC370-finalproject\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>JSC370 Final Project</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>